# We need to add this program prefix else its binaries will conflict with binutils
OPTS+=" --program-prefix=eu- \
        --disable-debuginfod \
        --enable-deterministic-archives"

default_build
