#!/bin/bash

[ ! -w /etc/ ] && exit 0

for ISSUE in /etc/issue /etc/issue.net ; do
  if [ -f /etc/lunar.release ] ; then
    cat /etc/lunar.release > $ISSUE
  else
    echo "Lunar Linux" > $ISSUE
  fi
  echo "Kernel `uname -r` on an `uname -m`" >> $ISSUE
  echo "" >> $ISSUE
done

