default_build &&
mv /etc/profile.d/bash_completion{.sh,.rc}

# remove Slackware's makepkg completion
rm /usr/share/bash-completion/completions/makepkg

# remove completions which overlap with util-linux
rm /usr/share/bash-completion/completions/{u,}mount
