
./configure --prefix=/usr \
            --bindir=/usr/bin \
            --mandir=/usr/share/man \
            --infodir=/usr/share/info \
            CPPFLAGS="$CPPFLAGS" \
            CFLAGS="$CFLAGS" \
            LDFLAGS="$LDFLAGS" &&

  default_make
