#! /bin/bash
#
# udev init script to setup /dev
# config: /etc/udev/udev.conf

case "$1" in

  start)
    rm -rf /dev/.udevdb
    export ACTION=add
    echo "Udev version `udevd --version` is starting"
    /sbin/udevd --daemon
    /sbin/udevadm trigger
    /sbin/udevadm settle
    # Wake up again lazy devices
    #/sbin/udevadm trigger --type=failed
    #/sbin/udevadm settle || exit 1;
    ;;

  stop)
    killall udevd
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1

esac

exit 0
