#!/bin/bash

LOCKFILE=/var/lock/makeupdatedb.lock
[ -f $LOCKFILE ] && exit 0

# source settings for updatedb (e.g. prunefs and prunepaths)
if [[ -f /etc/sysconfig/updatedb.conf ]] ; then
	. /etc/sysconfig/updatedb.conf
fi

trap "{ rm -f $LOCKFILE; exit 255; }" EXIT
touch $LOCKFILE
updatedb
exit 0
