#!/bin/sh

if  [  "$UID"  ==  0  ];  then

  if  [ "$1"="-r"  ];  then
    OPTS="-r"
    shift
  fi

  if  [  -z  "$1"  ];  then
    read  -p  "Username: "  DEADDUCK
  else
    DEADDUCK=$1
  fi

  /usr/bin/userdel  $OPTS  $DEADDUCK

else

  su  -  -c  "PATH=$PATH  $0  $1"

fi

