#!/bin/bash
#
# /etc/init.d/sysctl - set sysctl switches and parameters on startup
#
# description: sysctl is a frontend to the proc/sysctl kernel interface
#              where user modifieable parameters of the kernel may be
#              changed during normal kernel operation.

start () {
  if [ -f /etc/sysctl.conf ]; then
    echo -n "Setting up sysctl: "
    sysctl -p &&
    echo -e $RESULT_OK ||
    echo -e $RESULT_FAIL
  fi
}

stop () {
  :
}

. /lib/lsb/init-functions

