#!/bin/bash
# This network script takes care of running your favourite dhcp client
# on the interface you requested it to run on

NSCRIPT="/etc/init.d/network"

if [ -n "$1" ] && [ -n "$2" ] ; then
	if [ "$2" == "up" ]; then
		exec $NSCRIPT dhcp_up $1
	elif [ "$2" == "down" ]; then
		exec $NSCRIPT dhcp_down $1
	fi
fi

exit 0
