(

  ./configure  --build=$BUILD               \
               --prefix=/usr                \
               --infodir=/usr/share/info    \
               --mandir=/usr/share/man      \
               --datadir=/usr/share/bison  &&
  default_make

) > $C_FIFO 2>&1
