
OPTS+=" --enable-extras     \
        --enable-ntfsprogs  \
        --enable-posix-acls \
        --enable-crypto     \
        --enable-posix-acls \
        --enable-xattr-mappings \
        --disable-ldconfig  \
        --disable-static    \
        --mandir=/usr/share/man \
        --with-fuse=internal \
        --without-hd  \
        --exec-prefix=/usr" &&

default_build
