(

  default_build &&

  #the line below is for the "automake" symlink, needed by some sources
  rm -Rf /usr/share/automake &&
  ln -sf /usr/share/automake-${MAJOR} /usr/share/automake

) > $C_FIFO 2>&1
