#!/usr/bin/bash

# wget will be temporarily out of commission after installing libressl,
# so download a copy of its source code now while it still works
download_module wget

# Check to see if we're migrating from openssl to libressl
if module_installed libressl; then
   lrm libressl
   touch /var/state/lunar/migrating.from.libressl
fi
