name: Remove Label on New Commit

on:
  pull_request:
    types: [synchronize]

jobs:
  remove-label:
    if: contains(github.event.pull_request.labels.*.name, 'iso_ok')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Remove iso_ok label from PR
        uses: actions/github-script@v7
        with:
          script: |
            const labelToRemove = 'iso_ok';

            await github.issues.removeLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [labelToRemove],
            });
