# /etc/bashrc - global bashrc for non-interactive shells.

# the scripts that call this script expect a nicely setup environment
# for running scripts, not fancy prompts. So let's be restrictive
# by default:

# this is the minimum and given by init to start scripts (so a good start)
PATH=/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin

# these might not be present, so keep our path clean:
for DIR in /usr/local/bin /usr/X11/bin ; do
    [ -d $DIR ] && PATH="$PATH:$DIR"
done

# bare necessities:
export  PATH LANG=
umask   022

