# /etc/bashrc - global bashrc for non-interactive shells.

# the scripts that call this script expect a nicely setup environment
# for running scripts, not fancy prompts. So let's be restrictive
# by default:

# this is the minimum and given by init to start scripts (so a good start)
PATH="/usr/bin:."

# some of these might not be present, so keep our path clean:
for DIR in  ${HOME}/bin /usr/local/bin; do
  [ -d $DIR ] && PATH="$DIR:$PATH"
done

# bare necessities:
export PATH
umask  022
